# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='temp',
            field=models.FloatField(default=0, null=True),
        ),
    ]
