# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0003_auto_20160711_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='fecha_inicio',
        ),
    ]
