# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0011_sensor_url_dashboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervalo',
            old_name='corrimiento',
            new_name='pasos',
        ),
        migrations.AddField(
            model_name='intervalo',
            name='cache_pasos',
            field=models.IntegerField(blank=True, default=0, help_text='numero de datos seguidos a los que se activa la alarma, en 1 minuto son maximo 12 elementos', null=True),
        ),
    ]
