# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0012_auto_20160721_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='numero_pasos',
            field=models.FloatField(blank=True, default=0, help_text='numero de datos seguidos a los que se activa la alarma, en 1 minuto son maximo 12 elementos', null=True),
        ),
    ]
