# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0013_alerta_numero_pasos'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervalo',
            name='correo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intervalo',
            name='sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intervalo',
            name='telegrama',
            field=models.BooleanField(default=False),
        ),
    ]
