# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0014_auto_20160721_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervalo',
            name='nivel_critico_max',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='intervalo',
            name='nivel_critico_min',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
