# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0015_auto_20160722_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='punto_critico',
            field=models.BooleanField(default=False),
        ),
    ]
