# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0016_alerta_punto_critico'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='intervalo',
            name='pasos_normalizado',
            field=models.IntegerField(default=0, help_text='numero de datos seguidos a los que se considera que se apague la alarma en automatico', null=True),
        ),
        migrations.AlterField(
            model_name='intervalo',
            name='nivel_critico_max',
            field=models.FloatField(blank=True, default=0, help_text='tiene que ser un valor critico maximo, con 3 lecturas se activa', null=True),
        ),
        migrations.AlterField(
            model_name='intervalo',
            name='nivel_critico_min',
            field=models.FloatField(blank=True, default=0, help_text='tiene que ser un valor critico m\xednimo, con 3 lecturas se activa', null=True),
        ),
    ]
