# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0017_auto_20160725_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalo',
            name='pasos_normalizado',
            field=models.IntegerField(default=3, help_text='numero de datos seguidos a los que se considera que se apague la alarma en automatico', null=True),
        ),
    ]
