# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0018_auto_20160725_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='seconds_data_send',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
