# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0020_auto_20160729_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
