# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0021_sensor_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='numero_pasos',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='punto_critico',
        ),
        migrations.AddField(
            model_name='alerta',
            name='prob_critica',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='intervalo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.Intervalo'),
        ),
    ]
