# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0023_auto_20160803_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerta',
            old_name='seconds_data_send',
            new_name='seconds_to_check',
        ),
    ]
