# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0024_auto_20160803_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerta',
            old_name='estado',
            new_name='activa',
        ),
        migrations.AlterField(
            model_name='alerta',
            name='temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
