# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0025_auto_20160803_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervalo',
            name='cache_pasos',
        ),
        migrations.RemoveField(
            model_name='intervalo',
            name='minus_nivel_max',
        ),
        migrations.RemoveField(
            model_name='intervalo',
            name='minus_nivel_min',
        ),
        migrations.RemoveField(
            model_name='intervalo',
            name='nivel_critico_max',
        ),
        migrations.RemoveField(
            model_name='intervalo',
            name='nivel_critico_min',
        ),
        migrations.RemoveField(
            model_name='intervalo',
            name='pasos',
        ),
        migrations.RemoveField(
            model_name='intervalo',
            name='pasos_normalizado',
        ),
    ]
