# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 21:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoreo', '0026_auto_20160803_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorAlertado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True, null=True)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.Sensor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='user',
        ),
    ]
