# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 16:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0027_auto_20160803_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervalo',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='intervalo',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='intervalo',
        ),
        migrations.AddField(
            model_name='alerta',
            name='correo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alerta',
            name='persona',
            field=models.ManyToManyField(to='monitoreo.Persona'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoreo.Sensor'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alerta',
            name='telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alerta',
            name='tipo_nivel_alerta',
            field=models.CharField(choices=[('tolerable', 'tolerable'), ('critico', 'critico')], db_index=True, default='tolerable', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alerta',
            name='tipo_valor_de_alerta',
            field=models.CharField(choices=[('maximo', 'maximo'), ('minimo', 'minimo')], db_index=True, default='maximo', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alerta',
            name='valor_de_alerta',
            field=models.FloatField(default=-15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensoralertado',
            name='alerta',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitoreo.Alerta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensoralertado',
            name='fecha',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 4, 11, 43, 24, 203275)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensoralertado',
            name='temp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Intervalo',
        ),
    ]
