# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0029_auto_20160804_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensoralertado',
            name='activado',
            field=models.BooleanField(default=True),
        ),
    ]
