# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0030_sensoralertado_activado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='tipo_nivel_alerta',
        ),
        migrations.AddField(
            model_name='alerta',
            name='nivel_de_alerta',
            field=models.CharField(choices=[('tolerable', 'tolerable'), ('critico', 'critico')], db_index=True, default='tolerable', max_length=10, verbose_name='Nivel de alerta'),
            preserve_default=False,
        ),
    ]
