# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-14 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0031_auto_20160804_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensoralertado',
            name='mute_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
