# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-14 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0032_sensoralertado_mute_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensoralertado',
            name='alert_msg_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
