# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0033_sensoralertado_alert_msg_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensoralertado',
            name='sensor',
        ),
    ]
