# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-08 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0034_remove_sensoralertado_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='group_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='prob_critica',
            field=models.FloatField(default=0, verbose_name='Porcentaje'),
        ),
    ]
