# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-08 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0035_auto_20161208_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('c', 'continuos'), ('d', 'discrete')], default='c', max_length=2),
            preserve_default=False,
        ),
    ]
